
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint/eslint-plugin'
  - eslint-plugin-tsdoc
extends:
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/indent':
    - error
    - 2
    - SwitchCase: 1
      ignoredNodes:
        - TemplateLiteral *
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/no-namespace':
    - error
    - allowDeclarations: true
  '@typescript-eslint/camelcase': 0
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-explicit-any': off
  'tsdoc/syntax': 'error'
  indent:
    - error
    - 2
    - SwitchCase: 1
      ignoredNodes:
        - TemplateLiteral *
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: always-multiline
overrides:
  - files:
    - '**/test/*.spec.ts'
    env:
      mocha: true
